# Generated by Django 3.1.2 on 2020-11-02 16:20

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwwards', '0002_auto_20201102_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
